spring:
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:forum-rest-api
    username: sa
    password:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    defer-datasource-initialization: true
    properties:
      hibernate:
        format_sql: true